### ISSUE TITLE
may i use stateClient with emulator?

### ISSUE THREAD

**Issue by rainmakerho** [tsmatsuz/AuthDemoBot#2]
hi sir,  
AuthDemoWeb project HomeController's Authorize Method.
you use StateClient to store access token . 
stateClient.BotState.SetUserDataAsync("skype", Session["skypeuserid"].ToString(), botData);

it's also can use in emulator? 

thank for your help.

**Comment by tsmatsuz** [comment]
Yes, you can use bot state in emulator. In such case, in-memory implementation is used instead.


2017/05/18 17:51、亂馬客 <notifications@github.com<mailto:notifications@github.com>> のメッセージ:


hi sir,
AuthDemoWeb project HomeController's Authorize Method.
you use StateClient to store access token .
stateClient.BotState.SetUserDataAsync("skype", Session["skypeuserid"].ToString(), botData);

it's also can use in emulator?

thank for your help.

**Comment by rainmakerho** [comment]
thanks.
